(rule
 (targets main.exe)
 (deps main.c ../utilities/cuda_helpers.h ../utilities/cuda_helpers.c)
 (action
  (run
   clang
   -O2
   -I
   /usr/local/cuda/include
   -L
   /usr/local/cuda/lib64
   -Wl,-rpath,/usr/local/cuda/lib64
   -o
   %{targets}
   main.c
   ../utilities/cuda_helpers.c
   -lcuda
   -lnvrtc)))

(rule
 (alias lint-kernel)
 (deps
  kernel.cu
  (glob_files ../utilities/cuda_stubs/*))
 (action
  (run
   clang
   --cuda-device-only
   --cuda-gpu-arch=sm_89
   --cuda-path=/usr/local/cuda
   -I
   ../utilities/cuda_stubs
   -fsyntax-only
   -Wextra
   -Wgcc-compat
   -Wmissing-field-initializers
   -Wno-c++98-compat
   -Wno-c++98-compat-pedantic
   -Wno-unknown-cuda-version
   -Wno-missing-prototypes
   -Wno-unused-parameter
   -Wno-old-style-cast
   -Wno-unsafe-buffer-usage
   -Werror
   kernel.cu)))

(rule
 (alias lint)
 (deps main.c ../utilities/cuda_helpers.h ../utilities/cuda_helpers.c)
 (action
  (run
   clang
   -fsyntax-only
   -isystem/usr/local/cuda/include
   -Weverything
   -Wno-c++98-compat
   -Wno-c++98-compat-pedantic
   -Wno-unknown-cuda-version
   -Wno-missing-prototypes
   -Wno-old-style-cast
   -Wno-unsafe-buffer-usage
   -Wno-declaration-after-statement
   -Werror
   main.c)))
